//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Nullable<double> Номер_заказа { get; set; }
        public string Артикул_заказа { get; set; }
        public Nullable<System.DateTime> Дата_заказа { get; set; }
        public Nullable<System.DateTime> Дата_доставки { get; set; }
        public Nullable<double> Адрес_пункта_выдачи { get; set; }
        public string ФИО_авторизированного_клиента { get; set; }
        public Nullable<double> Код_для_получения { get; set; }
        public string Статус_заказа { get; set; }
        public int Id { get; set; }
    }
}
