//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovars
    {
        public int Id { get; set; }
        public string Артикул { get; set; }
        public string Наименование_товара { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<double> Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string Категория_товара { get; set; }
        public Nullable<double> Действующая_скидка { get; set; }
        public Nullable<double> Кол_во_на_складе { get; set; }
        public string Описание_товара { get; set; }
        public string Фото { get; set; }
    }
}
