//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovars
    {
        public string Артикул { get; set; }
        public string Наименование_товара { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<double> Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string Категория_товара { get; set; }
        public Nullable<double> Действующая_скидка { get; set; }
        public Nullable<double> Кол_во_на_складе { get; set; }
        public string Описание_товара { get; set; }
        public string Фото { get; set; }
        public int Id { get; set; }
    }
}
