// <auto-generated />
using System;
using Exam2026Prism.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exam2026Prism.Migrations
{
    [DbContext(typeof(Exam2026Context))]
    partial class Exam2026ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exam2026Prism.Context.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("АдресПунктаВыдачи")
                        .HasColumnType("float")
                        .HasColumnName("Адрес_пункта_выдачи");

                    b.Property<string>("АртикулЗаказа")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Артикул_заказа");

                    b.Property<DateTime?>("ДатаДоставки")
                        .HasColumnType("datetime")
                        .HasColumnName("Дата_доставки");

                    b.Property<DateTime?>("ДатаЗаказа")
                        .HasColumnType("datetime")
                        .HasColumnName("Дата_заказа");

                    b.Property<double?>("КодДляПолучения")
                        .HasColumnType("float")
                        .HasColumnName("Код_для_получения");

                    b.Property<double?>("НомерЗаказа")
                        .HasColumnType("float")
                        .HasColumnName("Номер_заказа");

                    b.Property<string>("СтатусЗаказа")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Статус_заказа");

                    b.Property<string>("ФиоАвторизированногоКлиента")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ФИО_авторизированного_клиента");

                    b.HasKey("Id")
                        .HasName("PK_orders");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Exam2026Prism.Context.PickUpPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Адрес")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_pickuppoints");

                    b.ToTable("PickUpPoints");
                });

            modelBuilder.Entity("Exam2026Prism.Context.Tovar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Артикул")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("ДействующаяСкидка")
                        .HasColumnType("float")
                        .HasColumnName("Действующая_скидка");

                    b.Property<string>("ЕдиницаИзмерения")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Единица_измерения");

                    b.Property<string>("КатегорияТовара")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Категория_товара");

                    b.Property<double?>("КолВоНаСкладе")
                        .HasColumnType("float")
                        .HasColumnName("Кол_во_на_складе");

                    b.Property<string>("НаименованиеТовара")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Наименование_товара");

                    b.Property<string>("ОписаниеТовара")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Описание_товара");

                    b.Property<string>("Поставщик")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Производитель")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Фото")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Цена")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK_tovars");

                    b.ToTable("Tovars");
                });

            modelBuilder.Entity("Exam2026Prism.Context.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Логин")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Пароль")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("РольСотрудника")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Роль_сотрудника");

                    b.Property<string>("Фио")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ФИО");

                    b.HasKey("Id")
                        .HasName("PK_users");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
